FROM node:14

RUN apt-get update && apt-get install -y wget \
    && wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz \
    && rm dockerize-linux-amd64-v0.6.1.tar.gz

WORKDIR /app

COPY . .

RUN npm install

EXPOSE 3000

CMD ["dockerize", "-wait", "tcp://db:3306", "-timeout", "20s", "npm", "start"]
